config/routes.rb
Rails.application.routes.draw do


  scope module: :public do
    root to: "homes#top"
    get "/about"=>"homes#about"
    resources :products, only: [:index, :show]
    resource :customers, only: [:show, :edit, :update] do
      get :check, on: :collection
      patch :withdrawal, on: :collection
      resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    end
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      delete :destroy_all, on: :collection
    end
    resources :orders, only: [:new, :create, :index, :show] do
      post :check, on: :collection
      get :complete, on: :collection
    end
    resources :genres, only: [:show]
  end

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }


  namespace :admin do
    root to: "homes#top"
    resources :products, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_products, only: [:update]
    get "search" => "searches#search"
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }

  get "search" => "searches#search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  validates :name, presence: true
  validates :address, presence: true, uniqueness: { scope: :customer_id }
  validates :postal_code, presence: true, length: { is: 7 }
  
   enum address_option: { "current_address": 0, "other_address": 1, "new_address": 2 }

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :customer


  def subtotal
    product.add_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # 退会処理用
  def active_for_authentication?
    super && (is_deleted == false)
  end

  def full_name
    self.last_name + self.first_name
  end

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders

  def self.looks(word)
    @customers = Customer.where(["last_name LIKE? OR first_name LIKE?","%#{word}%", "%#{word}%"])
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products

  validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer, dependent: :destroy
  has_many :order_products
  has_many :products, through: :order_products

  scope :latest, -> {order(created_at: :desc)}
  enum payment_type: { credit_card: 0, transfer: 1 }


  enum status: {
     "入金待ち":0,
     "入金確認":1,
     "製作中":2,
     "発送準備中":3,
     "発送済み":4
  }

  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true


end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
    belongs_to :order
    belongs_to :product
    
    enum makig_status: {
     "製作不可":0, 
     "製作待ち":1, 
     "製作中":2, 
     "製作完了":3, 
    }
  
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_products

  validates :name, presence: true, uniqueness: true
  validates :information, presence: true
  validates :price, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :is_active, inclusion: [true, false]

  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end

  def add_tax_price
    (price*1.1).floor
  end
  
  def self.looks(word)
    @product = Product.where("name LIKE?","%#{word}%")
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer=Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customer_path(customer.id)
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_num, :is_deleted, :email)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :last_name,
      :first_name,
      :last_name_kana,
      :first_name_kana,
      :postal_code,
      :address,
      :phone_num
    ])
  end
end

app/controllers/piblic/customers_controller.rb
class CustomersController < ApplicationController
  def show
  end

  def edit
  end

  def check
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @products = Product.looks(params[:word]).page(params[:page])
    @genres = Genre.all
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/admin/customers/edit.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col">
      <h3 class="mb-3"><span class="bg-light bg-gradient"><%= @customer.full_name %>さんの会員情報編集</span></h3>
      <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch, local:true, class: "container text-center pl-9" do |f| %>
      <div class="form-group row">
        <label class="col-3 pl-3">会員ID</label>
        <%= @customer.id %>
      </div>

      <div class="form-group row">
        <label class="col-3 pl-3">氏名</label>
        <%= f.text_field :last_name %>
        <%= f.text_field :first_name, class:'ml-5' %>
      </div>

      <div class="form-group row">
        <label class="col-3">フリガナ</label>
        <%= f.text_field :last_name_kana %>
        <%= f.text_field :first_name_kana, class: "ml-5" %>
      </div>

      <div class="form-group row">
        <label class="col-3">郵便番号</label>
        <%= f.text_field :postal_code %>
      </div>

      <div class="form-group row">
        <label class="col-3">住所</label>
        <%= f.text_field :address, class: "w-50" %>
      </div>

      <div class="form-group row">
        <label class="col-3">電話番号</label>
        <%= f.text_field :phone_num %>
      </div>

      <div class="form-group row">
        <label class="col-3">メールアドレス</label>
        <%= f.text_field :email %>
      </div>

      <div class="form-group row">
        <label class="col-3">会員ステータス</label>
        <%= f.radio_button :is_deleted, :false %>
        <%= f.label :is_deleted, "有効", value: "false", class: "mr-3" %>
        <%= f.radio_button :is_deleted, :true %>
        <%= f.label :is_deleted, "退会", value: "true" %>
      </div>

      <div class="form-group text-center">
        <%= f.submit "変更を保存", class: "btn btn-success btn-lg" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container my-5">
  <div class="row">
    <h4 class="mb-4 ml-5">会員一覧</h4>
  </div>
  <div class="row px-5">
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td><%= link_to customer.full_name,admin_customer_path(customer.id), class: "text-dark border-bottom border-dark" %></td>
          <td><%= customer.email %></td>
          <td>
            <% if customer.is_deleted == false %>
              <strong class="text-success">有効</strong>
            <% else %>
              <strong class="test-muted">退会</strong>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="row justify-content-center my-5">
    <%= paginate @customers %>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col">
      <h3><span class="bg-light bg-gradient"><%= @customer.full_name %>さんの会員詳細</span></h3>
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td class="w-25">会員ID</td>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <td class="w-25">氏名</td>
            <td><%= @customer.last_name %>　<%= @customer.first_name %></td>
          </tr>
          <tr>
            <td class="w-25">フリガナ</td>
            <td><%= @customer.last_name_kana %>　<%= @customer.first_name_kana %></td>
          </tr>
          <tr>
            <td class="w-25">郵便番号</td>
            <td><%= @customer.postal_code %></td>
          </tr>
          <tr>
            <td class="w-25">住所</td>
            <td><%= @customer.address %></td>
          </tr>
          <tr>
            <td class="w-25">電話番号</td>
            <td><%= @customer.phone_num %></td>
          </tr>
          <tr>
            <td class="w-25">メールアドレス</td>
            <td><%= @customer.email %></td>
          </tr>
          <tr>
            <td class="w-25">会員ステータス</td>
            <td>
              <% if @customer.is_deleted == false %>
                <strong class="text-success">有効</strong>
              <% else %>
                <strong class="text-denger">退会済み</strong>
              <%end%>
            </td>
          </tr>
        </tbody>
      </table>
      <div class="w-75 mx-auto">
        <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-lg btn-success mr-5" %>
        <%= link_to "注文履歴一覧を見る", admin_root_path, class: "btn btn-lg btn-primary" %>
      </div>
    </div>
  </div>
</div>