config/routes.rb
Rails.application.routes.draw do


  scope module: :public do
    root to: "homes#top"
    get "/about"=>"homes#about"
    resources :products, only: [:index, :show]
    resource :customers, only: [:show, :edit, :update] do
      get :check, on: :collection
      patch :withdrawal, on: :collection
      resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    end
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      delete :destroy_all, on: :collection
    end
    resources :orders, only: [:new, :create, :index, :show] do
      post :check, on: :collection
      get :complete, on: :collection
    end
    resources :genres, only: [:show]
  end

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }


  namespace :admin do
    root to: "homes#top"
    resources :products, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_products, only: [:update]
    get "search" => "searches#search"
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }

  get "search" => "searches#search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  validates :name, presence: true
  validates :address, presence: true, uniqueness: { scope: :customer_id }
  validates :postal_code, presence: true, length: { is: 7 }
  
   enum address_option: { "current_address": 0, "other_address": 1, "new_address": 2 }

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :customer


  def subtotal
    product.add_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # 退会処理用
  def active_for_authentication?
    super && (is_deleted == false)
  end

  def full_name
    self.last_name + self.first_name
  end

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders

  def self.looks(word)
    @customers = Customer.where(["last_name LIKE? OR first_name LIKE?","%#{word}%", "%#{word}%"])
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products

  validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer, dependent: :destroy
  has_many :order_products
  has_many :products, through: :order_products

  scope :latest, -> {order(created_at: :desc)}
  enum payment_type: { credit_card: 0, transfer: 1 }


  enum status: {
     "入金待ち":0,
     "入金確認":1,
     "製作中":2,
     "発送準備中":3,
     "発送済み":4
  }

  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true


end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
    belongs_to :order
    belongs_to :product
    
    enum makig_status: {
     "製作不可":0, 
     "製作待ち":1, 
     "製作中":2, 
     "製作完了":3, 
    }
  
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_products

  validates :name, presence: true, uniqueness: true
  validates :information, presence: true
  validates :price, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :is_active, inclusion: [true, false]

  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end

  def add_tax_price
    (price*1.1).floor
  end
  
  def self.looks(word)
    @product = Product.where("name LIKE?","%#{word}%")
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def show
    @order=Order.find(params[:id])
    @order_products=OrderProduct.where(order_id: @order.id)
  end
  
  def update
    @order=Order.find(params[:id])
    @order_products=OrderProduct.where(order_id: @order.id)
    if @order.update(order_params)
      @order_products.update_all(makig_status: 1) if @order.status == "入金確認"
    end
    redirect_to request.referer
  end
  
  private
  
  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :last_name,
      :first_name,
      :last_name_kana,
      :first_name_kana,
      :postal_code,
      :address,
      :phone_num
    ])
  end
end

app/controllers/piblic/orders_controller.rb
class OrdersController < ApplicationController
  def new
  end

  def check
  end

  def complete
  end

  def index
  end

  def show
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @products = Product.looks(params[:word]).page(params[:page])
    @genres = Genre.all
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/admin/orders/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col">
      <h3><span class="bg-light bg-gradient">注文履歴詳細</span></h3>
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td class="w-25"><strong>購入者</strong></td>
            <td><label class="border-bottom border-dark"><%= @order.customer.full_name %></label></td>
          </tr>
          <tr>
            <td class="w-25">注文日</td>
            <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
          </tr>
          <tr>
            <td class="w-25">配送先</td>
            <td><%= @order.address %></td>
          </tr>
          <tr>
            <td class="w-25">支払方法</td>
            <td><%= @order.payment_type %></td>
          </tr>
          <tr>
            <td class="w-25">注文ステータス</td>
            <td>
              <%= form_with model: @order, url: admin_order_path(@order.id), method: :patch, local:true do |f| %> 
                <%= f.select :status, Order.statuses.keys %>
                <%= f.submit "更新", class: "btn btn-success ml-3" %>
              <%end%>
            </td>
          </tr>
        </tbody>
      </table>
      
      <div class="row">
        <div class="col-9">
          <table class="table table-borderless border-top mt-3">
             <thead class="bg-light">
               <th class="border-top">商品ID</th>
                <th>商品名</th>
               <th>単価（税込）</th>
                <th>数量</th>
              <th>制作ステータス</th>
            </thead>
          <tbody>
              <% @order_products.each do |order_product| %>
                
                  <tr>
                    <td><%= order_product.id %></td>
                    <td><%= order_product.product.name %></td>
                    <td><%= order_product.price.to_s(:delimited) %></td>
                    <td><%= order_product.amount %></td>
                    <td>
                      <%= form_with model: order_product, url: admin_order_product_path(order_product.id), method: :patch, local:true do |f| %> 
                        <%= f.select :makig_status, OrderProduct.makig_statuses.keys %>
                        <%= f.submit "更新", class: "btn btn-success ml-3" %>
                      <%end%>
                    </td>
                  </tr>
                
              <%end%>
            </tbody>
          </table>
        </div>
      
        <div class="col-3 pl-5 d-flex align-items-end">
          <dl class="row">
            <dt class="col-6"><strong>商品合計</strong></dt>
            <dd class="col-6"><%= @order.total_payment - @order.shipping_cost %>円</dd>
            <dt class="col-6"><strong>送料</strong></dt>
            <dd class="col-6"><%= @order.shipping_cost %>円</dd>
            <dt class="col-6"><strong>請求金額合計</strong></dt>
            <dd class="col-6"><strong><%= @order.total_payment.to_s(:delimited) %>円</strong></dd>
          </dl>
        </div>
      </div>
    </div>
  </div>
</div>