config/routes.rb
Rails.application.routes.draw do


  scope module: :public do
    root to: "homes#top"
    get "/about"=>"homes#about"
    resources :products, only: [:index, :show]
    resource :customers, only: [:show, :edit, :update] do
      get :check, on: :collection
      patch :withdrawal, on: :collection
      resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    end
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      delete :destroy_all, on: :collection
    end
    resources :orders, only: [:new, :create, :index, :show] do
      post :check, on: :collection
      get :complete, on: :collection
    end
    resources :genres, only: [:show]
  end

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }


  namespace :admin do
    root to: "homes#top"
    resources :products, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_products, only: [:update]
    get "search" => "searches#search"
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }

  get "search" => "searches#search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  validates :name, presence: true
  validates :address, presence: true, uniqueness: { scope: :customer_id }
  validates :postal_code, presence: true, length: { is: 7 }
  
   enum address_option: { "current_address": 0, "other_address": 1, "new_address": 2 }

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :customer


  def subtotal
    product.add_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # 退会処理用
  def active_for_authentication?
    super && (is_deleted == false)
  end

  def full_name
    self.last_name + self.first_name
  end

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders

  def self.looks(word)
    @customers = Customer.where(["last_name LIKE? OR first_name LIKE?","%#{word}%", "%#{word}%"])
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products

  validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer, dependent: :destroy
  has_many :order_products
  has_many :products, through: :order_products

  scope :latest, -> {order(created_at: :desc)}
  enum payment_type: { credit_card: 0, transfer: 1 }


  enum status: {
     "入金待ち":0,
     "入金確認":1,
     "製作中":2,
     "発送準備中":3,
     "発送済み":4
  }

  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true


end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
    belongs_to :order
    belongs_to :product
    
    enum makig_status: {
     "製作不可":0, 
     "製作待ち":1, 
     "製作中":2, 
     "製作完了":3, 
    }
  
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_products

  validates :name, presence: true, uniqueness: true
  validates :information, presence: true
  validates :price, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :is_active, inclusion: [true, false]

  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end

  def add_tax_price
    (price*1.1).floor
  end
  
  def self.looks(word)
    @product = Product.where("name LIKE?","%#{word}%")
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         

end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  def search
    @range = params[:range]
    if admin_signed_in?
      if @range == "Product"
        @products = Product.looks(params[:word]).page(params[:page]).per(10)
      else
        @customers = Customer.looks(params[:word]).page(params[:page]).per(10)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :last_name,
      :first_name,
      :last_name_kana,
      :first_name_kana,
      :postal_code,
      :address,
      :phone_num
    ])
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @products = Product.looks(params[:word]).page(params[:page])
    @genres = Genre.all
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/search_helper.rb
module Admin::SearchHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/searches/search.html.erb
<% if admin_signed_in? %>
  <% if @range == "Product" %>
    <div class="container my-5">
      <div class="row">
        <div class="col-10">
          <h3><span class="bg-light bg-gradient">検索結果/商品一覧</span></h3>
        </div>
        <div class="col-2 ml-auto">
          <%= link_to "+", new_admin_product_path, class: "btn btn-lg rounded-pill shadow-sm" %>
        </div>
        <table class="table table-borderless border-top mt-3">
          <thead class="bg-light">
            <th class="border-top">商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </thead>
          <tbody>
            <% @products.each do |product| %>
              <tr>
                <td><%= product.id %></td>
                <td><%= link_to product.name, admin_product_path(product.id), class: "text-dark border-bottom border-dark" %></td>
                <td><%= product.price.to_s(:delimited) %></td>
                <td><%= product.genre.name %></td>
                <td>
                  <!--販売中と販売停止中で色を変えなければならないため、条件分岐で表示-->
                  <% if product.is_active == true %>
                    <strong class="text-success">販売中</strong>
                  <% else %>
                    <strong class="text-muted">販売停止中</strong>
                  <%end%>
                </td>
              </tr>
            <%end%>
          </tbody>
        </table>
        <div class="mx-auto mt-3">
          <%= paginate @products %>
        </div>
      </div>
    </div>
  <% else %>
    <div class="container my-5">
      <div class="row">
        <h4 class="mb-3 ml-5">検索結果/会員一覧</h4>
      </div>
      <div class="row px-5">
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>会員ID</th>
              <th>氏名</th>
              <th>メールアドレス</th>
              <th>ステータス</th>
            </tr>
          </thead>
          <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.id %></td>
              <td><%= link_to customer.full_name,admin_customer_path(customer.id), class: "text-dark border-bottom border-dark" %></td>
              <td><%= customer.email %></td>
              <td>
                <% if customer.is_deleted == false %>
                  <strong class="text-success">有効</strong>
                <% else %>
                  <strong class="test-muted">退会</strong>
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
      <div class="row justify-content-center">
        <%= paginate @customers %>
      </div>
    </div>
  <% end %>
<% else %>
  <div class='container px-5 px-sm-0 my-5'>
    <div class='row'>
      <div class='col-md-2'>
        <h5>ジャンル検索</h5>
        <%= render 'public/products/genres', genres: @genres %>
      </div>
      <div class='col-md-8 offset-md-1'>
        <div class='border-bottom form-group row form-inline'><h3>検索結果</h3><span>(全<%= @products.count %>件)</span></div>
        <%= render 'public/products/index', products: @products%>
      </div>
    </div>
    <div class="row justify-content-center">
      <%= paginate @products %>
    </div>
  </div>
<% end %>