config/routes.rb
Rails.application.routes.draw do


  scope module: :public do
    root to: "homes#top"
    get "/about"=>"homes#about"
    resources :products, only: [:index, :show]
    resource :customers, only: [:show, :edit, :update] do
      get :check, on: :collection
      patch :withdrawal, on: :collection
      resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    end
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      delete :destroy_all, on: :collection
    end
    resources :orders, only: [:new, :create, :index, :show] do
      post :check, on: :collection
      get :complete, on: :collection
    end
    resources :genres, only: [:show]
  end

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }


  namespace :admin do
    root to: "homes#top"
    resources :products, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_products, only: [:update]
    get "search" => "searches#search"
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }

  get "search" => "searches#search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  validates :name, presence: true
  validates :address, presence: true, uniqueness: { scope: :customer_id }
  validates :postal_code, presence: true, length: { is: 7 }
  
   enum address_option: { "current_address": 0, "other_address": 1, "new_address": 2 }

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :customer


  def subtotal
    product.add_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # 退会処理用
  def active_for_authentication?
    super && (is_deleted == false)
  end

  def full_name
    self.last_name + self.first_name
  end

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders

  def self.looks(word)
    @customers = Customer.where(["last_name LIKE? OR first_name LIKE?","%#{word}%", "%#{word}%"])
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products

  validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer, dependent: :destroy
  has_many :order_products
  has_many :products, through: :order_products

  scope :latest, -> {order(created_at: :desc)}
  enum payment_type: { credit_card: 0, transfer: 1 }


  enum status: {
     "入金待ち":0,
     "入金確認":1,
     "製作中":2,
     "発送準備中":3,
     "発送済み":4
  }

  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true


end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
    belongs_to :order
    belongs_to :product
    
    enum makig_status: {
     "製作不可":0, 
     "製作待ち":1, 
     "製作中":2, 
     "製作完了":3, 
    }
  
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_products

  validates :name, presence: true, uniqueness: true
  validates :information, presence: true
  validates :price, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :is_active, inclusion: [true, false]

  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end

  def add_tax_price
    (price*1.1).floor
  end
  
  def self.looks(word)
    @product = Product.where("name LIKE?","%#{word}%")
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @products=Product.page(params[:page]).per(10)
  end

  def new
    @product=Product.new
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product=Product.find(params[:id])
  end

  def create
    @product=Product.new(product_params)
    if @product.save
      redirect_to admin_product_path(@product.id)
    else
      flash[:danger]="入力内容に不備があります。<br>・#{@product.errors.full_messages.join('<br>・')}"
      redirect_to new_admin_product_path
    end
  end

  def update
    @product=Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_product_path(@product.id)
    else
      flash[:danger]="入力内容に不備があります。<br>・#{@product.errors.full_messages.join('<br>・')}"
      redirect_to edit_admin_product_path(@product.id)
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :information, :image, :genre_id, :price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :last_name,
      :first_name,
      :last_name_kana,
      :first_name_kana,
      :postal_code,
      :address,
      :phone_num
    ])
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @products = Product.looks(params[:word]).page(params[:page])
    @genres = Genre.all
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/admin/products/edit.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-md-10 col-sm-12 mx-6 mx-sm-auto px-auto">
      <div class="row d-flex justify-content-center mb-4">
        <h3 class="col-6"><span>商品編集</span></h3>
      </div>
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= sanitize message, tags: %w(br) %></div>
        <%end%>

        <%= form_with model: @product, url: admin_product_path(@product.id), method: :patch, local:true, class: "container text-center pl-9" do |f| %>
        <div class="form-group row">
          <label class="col-4 text-right">商品画像</label>
          <%= f.file_field :image, class: "col-4 form-control-file pl-0", accept: "image/*" %>
        </div>
        <div class="form-group row">
          <label class="col-4 text-right">商品名</label>
          <%= f.text_field :name, class: "col-4 form-control name", placeholder: "商品名" %>
        </div>
        <div class="form-group row">
          <label class="col-4 text-right">商品説明</label>
          <%= f.text_area :information, class: "col-4 form-control information", placeholder: "ここに説明文を記述します" %>
        </div>
        <div class="form-group row">
          <label class="col-4 text-right">ジャンル</label>
          <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択してください--" %>
        </div>
        <div class="form-group row">
          <label class="col-4 text-right">税抜価格</label>
          <%= f.text_field :price, class: "col-4 form-control price", placeholder: "1000" %>円
        </div>
        <div class="form-group row">
          <label class="col-4 text-right">販売ステータス</label>
          <%= f.radio_button :is_active, :true %>
          <%= f.label :is_active, "販売中", value: "true", class: "mr-5" %>
          <%= f.radio_button :is_active, :false %>
          <%= f.label :is_active, "販売停止中", value: "false" %>
        </div>
        <div class="form-group text-center mt-5">
          <%= f.submit "変更を保存", class: "btn btn-success btn-lg" %>
        </div>
        <%end%>
    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-10">
      <h3><span class="bg-light bg-gradient">商品一覧</span></h3>
    </div>
    <div class="col-2 ml-auto">
      <%= link_to "+", new_admin_product_path, class: "btn btn-lg rounded-pill border shadow-sm" %>
    </div>
    <table class="table table-borderless border-top mt-3">
      <thead class="bg-light">
        <th class="border-top">商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th>ステータス</th>
      </thead>
      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td><%= product.id %></td>
            <td><%= link_to product.name, admin_product_path(product.id), class: "text-dark border-bottom border-dark" %></td>
            <td><%= product.price.to_s(:delimited) %></td>
            <td><%= product.genre.name %></td>
            <td>
              <!--販売中と販売停止中で色を変えなければならないため、条件分岐で表示-->
              <% if product.is_active == true %>
                <strong class="text-success">販売中</strong>
              <% else %>
                <strong class="text-muted">販売停止中</strong>
              <%end%>
            </td>
          </tr>
        <%end%>
      </tbody>
    </table>
    <div class="mx-auto mt-5">
      <%= paginate @products %>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-md-10 col-sm-12 mx-6 mx-sm-auto px-auto">
        <h3 class="mb-5 col-8 d-flex justify-content-center"><span>商品新規登録</span></h3>

        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= sanitize message, tags: %w(br) %></div>
        <%end%>

        <%= form_with model: @product, url: admin_products_path, method: :post, local:true do |f| %>
          <div class="w-50 mx-auto">
              <dl class="row">
                <dt class="col-4"><%= f.label :image, "商品画像", class: "text-right" %></dt>
                <dd class="col-8"><%= f.file_field :image, class: "form-control-file pl-0", accept: "image/*" %></dd>

                <dt class="col-4 mt-3"><%= f.label :name, "商品名", class: "text-right" %></dt>
                <dd class="col-8 mt-3"><%= f.text_field :name, class: "form-control name", placeholder: "商品名" %></dd>

                <dt class="col-4 mt-3"><%= f.label :information, "商品説明", class: "text-right" %></dt>
                <dd class="col-8 mt-3"><%= f.text_area :information, class: "form-control information", placeholder: "ここに説明文を記述します" %></dd>

                <dt class="col-4 mt-3"><%= f.label :genre_id, "ジャンル", class: "text-right" %></dt>
                <dd class="col-8 mt-3"><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択してください--" %></dd>

                <dt class="col-4 mt-3"><%= f.label :price, "税抜価格", class: "text-right" %></dt>
                <dd class="col-8 mt-3 input-group d-flex align-items-end"><%= f.text_field :price, class: "form-control price", placeholder: "1000" %>円</dd>

                <dt class="col-4 mt-3"><label class="text-right">販売ステータス</label></dt>
                <dd class="col-8 mt-3">
                  <%= f.radio_button :is_active, :true %>
                  <%= f.label :is_active, "販売中", value: "true", class: "mr-5" %>
                  <%= f.radio_button :is_active, :false %>
                  <%= f.label :is_active, "販売停止中", value: "false" %>
                </dd>
              </dl>
          </div>

        <div class="form-group text-center">
          <%= f.submit "新規登録", class: "btn btn-success btn-lg" %>
        </div>
        <%end%>
    </div>
  </div>
</div>

app/views/admin/products/show.html.erb
<div class="container">
  <div class="row mt-5">
    <h3 class="mb-5 ml-5">商品詳細</h3>
  </div>
  <div class="row">
    <div class="col-md-4">
      <%= image_tag @product.get_image, size: '300x200', class:"shadow img-thumbnail" %>
    </div>
    <div class="col-md-8">
      <div class="form-group row">
        <p class="col-3 h5">商品名</p>
        <p class="col-8"><%= @product.name %></p>
      </div>
      <div class="form-group row">
        <p class="col-3 h5">商品説明</p>
        <p class="col-8"><%= @product.information %></p>
      </div>
      <div class="form-group row">
        <p class="col-3 h5">ジャンル</p>
        <p class="col-8"><%= @product.genre.name %></p>
      </div>
      <div class="form-group row">
        <p class="col-3 h5">税込価格<br>(税抜価格)</p>
        <p class="col-8"><%= @product.add_tax_price.to_s(:delimited) %>（<%= @product.price.to_s(:delimited) %>）円</p>
      </div>
      <div class="form-group row">
        <p class="col-3 h5">販売ステータス</p>
        <p class="col-8"><%= @product.is_active ? '販売中' : '販売停止中' %></p>
      </div>
    </div>
  </div>
  <div class="form-group text-center my-5">
      <%= link_to "編集する", edit_admin_product_path, class: "btn btn-success btn-lg" %>
    </div>
</div>